// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7BGu1MiHNFuTkZyQT8AGx5a7SxFJ6EoY',
    appId: '1:321721482843:web:1d0575b7c886878393497e',
    messagingSenderId: '321721482843',
    projectId: 'inkvault-e8d90',
    authDomain: 'inkvault-e8d90.firebaseapp.com',
    storageBucket: 'inkvault-e8d90.firebasestorage.app',
    measurementId: 'G-Q4781S1HWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrJ_bSm9Nypyi4tGSm5AElvRh2FBNXcqY',
    appId: '1:321721482843:android:753a4b2efa82900793497e',
    messagingSenderId: '321721482843',
    projectId: 'inkvault-e8d90',
    storageBucket: 'inkvault-e8d90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRi50t1FagXzG4c7uedC7XqdOufDtVBx4',
    appId: '1:321721482843:ios:98417945d4994c8b93497e',
    messagingSenderId: '321721482843',
    projectId: 'inkvault-e8d90',
    storageBucket: 'inkvault-e8d90.firebasestorage.app',
    iosBundleId: 'com.example.inkvault2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRi50t1FagXzG4c7uedC7XqdOufDtVBx4',
    appId: '1:321721482843:ios:98417945d4994c8b93497e',
    messagingSenderId: '321721482843',
    projectId: 'inkvault-e8d90',
    storageBucket: 'inkvault-e8d90.firebasestorage.app',
    iosBundleId: 'com.example.inkvault2',
  );
}
